import {
  PensumModule,
  StudentModuleGrade,
  SalonPracticeRecord,
  StudentObserverEntry,
  AcademyNotice,
  TeacherStudentMsg,
} from '../types';

export const INITIAL_PENSUM_MODULES: PensumModule[] = [
  // Programa: Técnico Laboral en Peluquería Integral & Estilismo
  {
    id: 'mod-pel-01',
    code: 'MOD-PEL-01',
    name: 'Bioseguridad, Higiene & Asepsia en Salón de Belleza',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 1,
    theoryHours: 30,
    practiceHours: 20,
    totalHours: 50,
    competencies: [
      'Protocolos de esterilización en autoclave y rayos UV',
      'Manejo seguro de residuos biológicos y cortopunzantes (guardián)',
      'Uso adecuado de EPP (bata antifluidos, guantes de nitrilo, tapabocas)',
      'Normatividad y resolución de la Secretaría de Salud para centros de estética y peluquería',
    ],
    description:
      'Fundamentos normativos indispensables para el ejercicio profesional seguro del estilista, asepsia del mobiliario y prevención de riesgos biológicos.',
    order: 1,
  },
  {
    id: 'mod-pel-02',
    code: 'MOD-PEL-02',
    name: 'Tricología, Diagnóstico Capilar & Masaje de Lavacabezas',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 1,
    theoryHours: 25,
    practiceHours: 35,
    totalHours: 60,
    competencies: [
      'Estructura de la hebra capilar: cutícula, córtex y médula',
      'Test de elasticidad, porosidad y resistencia al quiebre',
      'Técnica ergonómica de lavado capilar con masaje relajante craneal',
      'Identificación de anomalías (pitiriasis, seborrea, alopecia, tricoptilosis)',
    ],
    prerequisites: 'MOD-PEL-01',
    description:
      'Estudio científico del cabello y cuero cabelludo para emitir diagnósticos acertados y ofrecer tratamientos personalizados.',
    order: 2,
  },
  {
    id: 'mod-pel-03',
    code: 'MOD-PEL-03',
    name: 'Técnicas de Corte Femenino & Brushing Modelador',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 1,
    theoryHours: 20,
    practiceHours: 70,
    totalHours: 90,
    competencies: [
      'Ángulos de corte fundamentales (0°, 45°, 90°, 135°, 180°)',
      'Líneas de partición: horizontal, vertical, diagonal anterior y posterior',
      'Corte sólido, degrafilado, capas progresivas, Bob clásico y Pixie',
      'Brushing profesional con secador iónico y cepillos térmicos redondos',
    ],
    prerequisites: 'MOD-PEL-01, MOD-PEL-02',
    description:
      'Dominio de la tijera recta, microdentada y de entresacar para esculpir cortes geométricos precisos combinados con modelado térmico de impacto.',
    order: 3,
  },
  {
    id: 'mod-pel-04',
    code: 'MOD-PEL-04',
    name: 'Colorimetría Básica & Cubrimiento Óptimo de Canas',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 2,
    theoryHours: 30,
    practiceHours: 50,
    totalHours: 80,
    competencies: [
      'Círculo cromático de Ostwald y leyes universales del color',
      'Fondos naturales de pigmentación y escala de alturas de tono (1 al 10)',
      'Regla del 11 para neutralización de reflejos indeseados',
      'Mordentado y formulación con bases naturales (.0 / .00) sobre canas rebeldes',
    ],
    prerequisites: 'MOD-PEL-02',
    description:
      'Cálculo y aplicación exacta de pigmentos oxidativos directos e indirectos para transformaciones de color impecables y cobertura 100% de canicie.',
    order: 4,
  },
  {
    id: 'mod-pel-05',
    code: 'MOD-PEL-05',
    name: 'Decoloración Avanzada, Babylights & Balayage Esfumado',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 2,
    theoryHours: 25,
    practiceHours: 65,
    totalHours: 90,
    competencies: [
      'Fondos de aclaración 8, 9 y 10 sin comprometer la elasticidad capilar',
      'Técnicas de empapelado térmico, cardado (teasing) y mano alzada (freehand)',
      'Falsos crecimientos (shadow root) y transiciones difuminadas',
      'Matización precisa y sellado ácido de cutícula post-decoloración',
    ],
    prerequisites: 'MOD-PEL-04',
    description:
      'La especialidad más demandada en salones de lujo: diseño de mechas multidimensionales, contouring facial y rubios platinados o beige.',
    order: 5,
  },
  {
    id: 'mod-pel-06',
    code: 'MOD-PEL-06',
    name: 'Barbería Clásica, Degradado Fade Urbano & Barba',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 2,
    theoryHours: 20,
    practiceHours: 50,
    totalHours: 70,
    competencies: [
      'Manejo de máquinas clípper profesionales y juego de guías (0.5 a 4)',
      'Técnica de Low Fade, Mid Fade, High Fade y Taper Fade',
      'Perfilado y rasurado con navaja barbera de hoja intercambiable',
      'Ritual de barba con toalla caliente aromatizada y aceites emolientes',
    ],
    prerequisites: 'MOD-PEL-01, MOD-PEL-03',
    description:
      'Técnicas modernas de barbería masculina, difuminados limpios milímetro a milímetro y diseño simétrico de barbas y bigotes.',
    order: 6,
  },
  {
    id: 'mod-pel-07',
    code: 'MOD-PEL-07',
    name: 'Tratamientos Capilares, Alisados Orgánicos & Nanoplastia',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 2,
    theoryHours: 20,
    practiceHours: 40,
    totalHours: 60,
    competencies: [
      'Alisados progresivos con ácido hialurónico, taninos y aminoácidos 100% libres de formol',
      'Cauterización capilar molecular y botox reconstructivo con colágeno',
      'Temperatura y pasadas de plancha de titanio según grosor capilar',
      'Recomendación de cronograma capilar (hidratación, nutrición y reconstrucción)',
    ],
    prerequisites: 'MOD-PEL-02',
    description:
      'Reestructuración de fibras maltratadas y alisados termosellados con brillo espejo duradero garantizando la salud del cliente.',
    order: 7,
  },
  {
    id: 'mod-pel-08',
    code: 'MOD-PEL-08',
    name: 'Salón Escuela & Prácticas Integrales con Modelos Reales',
    program: 'Técnico Laboral en Peluquería Integral',
    cycleOrSemester: 2,
    theoryHours: 10,
    practiceHours: 90,
    totalHours: 100,
    competencies: [
      'Atención y asesoría de imagen integral al cliente en salón escuela',
      'Cronometraje profesional y rendimiento de tiempos de atención',
      'Cobro de servicios, manejo de agenda y fidelización',
      'Sustentación del book de trabajos prácticos ante jurado docente',
    ],
    prerequisites: 'Aprobación de MOD-PEL-01 al MOD-PEL-07',
    description:
      'Inmersión real en el salón escuela de Arte & Estilo. El estudiante atiende clientes reales bajo la supervisión de docentes evaluadores.',
    order: 8,
  },

  // Programa: Barbería Profesional & Barber Shop Master
  {
    id: 'mod-bar-01',
    code: 'MOD-BAR-01',
    name: 'Bioseguridad en Barbería & Afilado de Herramientas',
    program: 'Barbería Profesional & Fade',
    cycleOrSemester: 1,
    theoryHours: 20,
    practiceHours: 20,
    totalHours: 40,
    competencies: [
      'Desinfección de cuchillas con bactericidas y spray enfriador',
      'Cambio seguro de hojillas de afeitar y desecho en guardián',
      'Mantenimiento preventivo, calibrado y alineación de máquinas clípper',
    ],
    description: 'Protocolos de bioseguridad específicos para barberías de alto tráfico.',
    order: 1,
  },
  {
    id: 'mod-bar-02',
    code: 'MOD-BAR-02',
    name: 'Morfología Craneal & Cortes Clásicos a Tijera',
    program: 'Barbería Profesional & Fade',
    cycleOrSemester: 1,
    theoryHours: 25,
    practiceHours: 45,
    totalHours: 70,
    competencies: [
      'Análisis de la forma craneal y visajismo masculino',
      'Técnicas de tijera sobre peine (scissor over comb)',
      'Corte clásico ejecutivo, Pompadour, Quiff y textura superior',
    ],
    description: 'Corte tradicional de caballero con acabados elegantes y líneas naturales.',
    order: 2,
  },
  {
    id: 'mod-bar-03',
    code: 'MOD-BAR-03',
    name: 'Degradados Urbanos (Skin Fade, Burst Fade, Mullet)',
    program: 'Barbería Profesional & Fade',
    cycleOrSemester: 1,
    theoryHours: 20,
    practiceHours: 60,
    totalHours: 80,
    competencies: [
      'Eliminación de líneas duras con shaver y trimmer',
      'Transición perfecta de 0 a 1.5 con movimiento en C (scoop motion)',
      'Diseños urbanos modernos: Burst Fade, Taper Fade y Modern Mullet',
    ],
    description: 'Técnicas avanzadas de desvanecido urbano que marcan tendencia en la industria.',
    order: 3,
  },
  {
    id: 'mod-bar-04',
    code: 'MOD-BAR-04',
    name: 'Diseño de Barba, Toalla Caliente & Pigmentación',
    program: 'Barbería Profesional & Fade',
    cycleOrSemester: 1,
    theoryHours: 15,
    practiceHours: 45,
    totalHours: 60,
    competencies: [
      'Apertura de poros con toalla húmeda caliente a vapor',
      'Perfilado milimétrico de mejillas y cuello con navaja',
      'Aplicación de pigmento temporal con aerógrafo para barbas tupidas',
    ],
    description: 'Experiencia premium de barbería spa para el cuidado de la barba masculina.',
    order: 4,
  },
];

export const INITIAL_MODULE_GRADES: StudentModuleGrade[] = [
  // Sofía Ramírez Díaz (usr-stud-1)
  {
    id: 'mgr-sof-1',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    studentDocument: 'TI 1.025.789.444',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    moduleId: 'mod-pel-01',
    moduleCode: 'MOD-PEL-01',
    moduleName: 'Bioseguridad, Higiene & Asepsia en Salón de Belleza',
    theoryScore: 4.8,
    practiceScore: 5.0,
    biosecurityScore: 5.0,
    finalScore: 4.9,
    status: 'aprobado',
    feedback: 'Impecable presentación personal, conocimiento total del protocolo de bioseguridad y autoclave.',
    teacherId: 'usr-teach-1',
    teacherName: 'Prof. Elena Restrepo',
    updatedAt: '2026-02-28',
  },
  {
    id: 'mgr-sof-2',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    studentDocument: 'TI 1.025.789.444',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    moduleId: 'mod-pel-02',
    moduleCode: 'MOD-PEL-02',
    moduleName: 'Tricología, Diagnóstico Capilar & Masaje de Lavacabezas',
    theoryScore: 4.6,
    practiceScore: 4.8,
    biosecurityScore: 4.9,
    finalScore: 4.7,
    status: 'aprobado',
    feedback: 'Excelente técnica de masaje craneal en lavacabezas y diagnóstico con microscopio capilar.',
    teacherId: 'usr-teach-1',
    teacherName: 'Prof. Elena Restrepo',
    updatedAt: '2026-03-05',
  },
  {
    id: 'mgr-sof-3',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    studentDocument: 'TI 1.025.789.444',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    moduleId: 'mod-pel-03',
    moduleCode: 'MOD-PEL-03',
    moduleName: 'Técnicas de Corte Femenino & Brushing Modelador',
    theoryScore: 4.4,
    practiceScore: 4.8,
    biosecurityScore: 4.7,
    finalScore: 4.7,
    status: 'aprobado',
    feedback: 'Corte degrafilado a 90° con simetría exacta. Brushing con volumen y sellado de puntas perfecto.',
    teacherId: 'usr-teach-1',
    teacherName: 'Prof. Elena Restrepo',
    updatedAt: '2026-03-12',
  },
  {
    id: 'mgr-sof-4',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    studentDocument: 'TI 1.025.789.444',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    moduleId: 'mod-pel-04',
    moduleCode: 'MOD-PEL-04',
    moduleName: 'Colorimetría Básica & Cubrimiento Óptimo de Canas',
    theoryScore: 4.7,
    practiceScore: 4.9,
    biosecurityScore: 5.0,
    finalScore: 4.9,
    status: 'aprobado',
    feedback: 'Dominio absoluto de la regla del 11 y mordentado. Cobertura del 100% en modelo con 80% de canas.',
    teacherId: 'usr-teach-1',
    teacherName: 'Prof. Elena Restrepo',
    updatedAt: '2026-03-18',
  },
  {
    id: 'mgr-sof-5',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    studentDocument: 'TI 1.025.789.444',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    moduleId: 'mod-pel-07',
    moduleCode: 'MOD-PEL-07',
    moduleName: 'Tratamientos Capilares, Alisados Orgánicos & Nanoplastia',
    theoryScore: 4.5,
    practiceScore: 4.6,
    biosecurityScore: 4.8,
    finalScore: 4.6,
    status: 'aprobado',
    feedback: 'Planchado térmico a 450°F uniforme sin quemar las puntas. Cabello sedoso con brillo espejo.',
    teacherId: 'usr-teach-1',
    teacherName: 'Prof. Elena Restrepo',
    updatedAt: '2026-03-20',
  },
  {
    id: 'mgr-sof-6',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    studentDocument: 'TI 1.025.789.444',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    moduleId: 'mod-pel-05',
    moduleCode: 'MOD-PEL-05',
    moduleName: 'Decoloración Avanzada, Babylights & Balayage Esfumado',
    theoryScore: 4.3,
    practiceScore: 4.5,
    biosecurityScore: 4.6,
    finalScore: 4.5,
    status: 'en_curso',
    feedback: 'Actualmente realizando prácticas de esfumado con cardado. Excelente cuidado de la fibra capilar.',
    teacherId: 'usr-teach-1',
    teacherName: 'Prof. Elena Restrepo',
    updatedAt: '2026-03-22',
  },

  // Mateo Castro Gómez (usr-stud-2)
  {
    id: 'mgr-mat-1',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    studentDocument: 'TI 1.032.441.982',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    moduleId: 'mod-pel-01',
    moduleCode: 'MOD-PEL-01',
    moduleName: 'Bioseguridad, Higiene & Asepsia en Salón de Belleza',
    theoryScore: 4.2,
    practiceScore: 4.4,
    biosecurityScore: 4.5,
    finalScore: 4.3,
    status: 'aprobado',
    feedback: 'Aprobó satisfactoriamente el examen de esterilización de herramientas de corte y navaja.',
    teacherId: 'usr-teach-2',
    teacherName: 'Prof. Marcos Silva',
    updatedAt: '2026-03-01',
  },
  {
    id: 'mgr-mat-2',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    studentDocument: 'TI 1.032.441.982',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    moduleId: 'mod-pel-06',
    moduleCode: 'MOD-PEL-06',
    moduleName: 'Barbería Clásica, Degradado Fade Urbano & Barba',
    theoryScore: 4.6,
    practiceScore: 4.8,
    biosecurityScore: 4.6,
    finalScore: 4.7,
    status: 'aprobado',
    feedback: 'Muy buena soltura con la máquina Wahl y navaja libre. El Low Fade quedó muy limpio.',
    teacherId: 'usr-teach-2',
    teacherName: 'Prof. Marcos Silva',
    updatedAt: '2026-03-15',
  },
  {
    id: 'mgr-mat-3',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    studentDocument: 'TI 1.032.441.982',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    moduleId: 'mod-pel-02',
    moduleCode: 'MOD-PEL-02',
    moduleName: 'Tricología, Diagnóstico Capilar & Masaje de Lavacabezas',
    theoryScore: 3.9,
    practiceScore: 4.2,
    biosecurityScore: 4.0,
    finalScore: 4.1,
    status: 'aprobado',
    feedback: 'Identificó correctamente tipos de cuero cabelludo graso y seco.',
    teacherId: 'usr-teach-2',
    teacherName: 'Prof. Marcos Silva',
    updatedAt: '2026-03-10',
  },
  {
    id: 'mgr-mat-4',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    studentDocument: 'TI 1.032.441.982',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    moduleId: 'mod-pel-03',
    moduleCode: 'MOD-PEL-03',
    moduleName: 'Técnicas de Corte Femenino & Brushing Modelador',
    theoryScore: 3.7,
    practiceScore: 3.9,
    biosecurityScore: 4.0,
    finalScore: 3.9,
    status: 'en_curso',
    feedback: 'Módulo en desarrollo. Se recomienda practicar más la técnica de capas a 90° con modelo.',
    teacherId: 'usr-teach-1',
    teacherName: 'Prof. Elena Restrepo',
    updatedAt: '2026-03-21',
  },
];

export const INITIAL_PRACTICE_RECORDS: SalonPracticeRecord[] = [
  {
    id: 'prac-rec-1',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    date: '2026-03-19',
    serviceCategory: 'Colorimetría Avanzada & Balayage',
    modelClientName: 'Camila Andrea Torres (Modelo Externa)',
    modelClientPhone: '+57 311 445 6677',
    serviceDescription:
      'Diseño Balayage Rubio Vainilla con técnica de cardado al 40%. Neutralización de fondo 9 y esfumado de raíz con falso crecimiento.',
    technicalFormulas:
      'Decolorante Blondor 1:2 con peróxido 20 vol + Plex protector. Matiz: 9.13 (30g) + 9.2 (10g) con 10 vol por 15 minutos en lavacabezas.',
    practiceHours: 4.5,
    supervisorTeacherId: 'usr-teach-1',
    supervisorTeacherName: 'Prof. Elena Restrepo',
    status: 'aprobado',
    score: 4.9,
    teacherObservations:
      'Excelente difuminado sin líneas de corte. La textura capilar quedó hidratada y el tono rubio vainilla muy limpio.',
    verifiedSignature: true,
    createdAt: '2026-03-19 05:30 PM',
  },
  {
    id: 'prac-rec-2',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    date: '2026-03-16',
    serviceCategory: 'Corte de Cabello Femenino/Masculino',
    modelClientName: 'Mariana Duque Soler',
    modelClientPhone: '+57 315 889 1122',
    serviceDescription:
      'Corte Long Bob texturizado en puntas con particiones diagonales posteriores y brushing con movimiento hacia adentro.',
    technicalFormulas: 'Protector térmico de argán + sérum antifrizz de sellado.',
    practiceHours: 3.0,
    supervisorTeacherId: 'usr-teach-1',
    supervisorTeacherName: 'Prof. Elena Restrepo',
    status: 'aprobado',
    score: 4.8,
    teacherObservations:
      'Línea de caída limpia y pulida. Correcto uso de tijera de entresacar para aligerar peso en laterales.',
    verifiedSignature: true,
    createdAt: '2026-03-16 03:00 PM',
  },
  {
    id: 'prac-rec-3',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    date: '2026-03-14',
    serviceCategory: 'Tratamientos Capilares & Alisados',
    modelClientName: 'Diana Marcela Castro',
    modelClientPhone: '+57 320 771 9900',
    serviceDescription:
      'Alisado orgánico a base de aminoácidos y ácido hialurónico libre de formol. Tiempo de pose 45 min y planchado a 430°F.',
    technicalFormulas: 'Kit Nanoplastia Pro Therapy 120ml.',
    practiceHours: 4.0,
    supervisorTeacherId: 'usr-teach-1',
    supervisorTeacherName: 'Prof. Elena Restrepo',
    status: 'aprobado',
    score: 4.7,
    teacherObservations:
      'Técnica de mechones finos bien ejecutada. El cabello quedó con caída natural y 100% sellado.',
    verifiedSignature: true,
    createdAt: '2026-03-14 06:15 PM',
  },
  {
    id: 'prac-rec-4',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    date: '2026-03-18',
    serviceCategory: 'Barbería, Fade & Barba',
    modelClientName: 'Andrés Felipe Morales',
    modelClientPhone: '+57 314 220 5511',
    serviceDescription:
      'Mid Fade con afeitado a piel usando shaver en contornos inferiores. Corte a tijera en zona superior con textura y peinado hacia atrás con pomada mate.',
    technicalFormulas: 'Gel de afeitar transparente de menta + After shave balsámico sin alcohol.',
    practiceHours: 2.5,
    supervisorTeacherId: 'usr-teach-2',
    supervisorTeacherName: 'Prof. Marcos Silva',
    status: 'aprobado',
    score: 4.8,
    teacherObservations:
      'Borrado de la línea guía de la 0 impecable. Buen ángulo con la navaja en contornos de patilla.',
    verifiedSignature: true,
    createdAt: '2026-03-18 04:30 PM',
  },
  {
    id: 'prac-rec-5',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    date: '2026-03-21',
    serviceCategory: 'Barbería, Fade & Barba',
    modelClientName: 'Carlos Eduardo Peña',
    modelClientPhone: '+57 317 662 3344',
    serviceDescription:
      'Ritual de barba completa: toalla caliente a vapor, perfilado de mejilla con navaja y rebaje de volumen con tijera sobre peine.',
    technicalFormulas: 'Aceite de eucalipto + bálsamo fijador con cera de abejas.',
    practiceHours: 2.0,
    supervisorTeacherId: 'usr-teach-2',
    supervisorTeacherName: 'Prof. Marcos Silva',
    status: 'aprobado',
    score: 4.6,
    teacherObservations:
      'Buen manejo de la toalla caliente. Cuidar no presionar en exceso la navaja sobre la nuez de Adán.',
    verifiedSignature: true,
    createdAt: '2026-03-21 11:45 AM',
  },
];

export const INITIAL_OBSERVER_ENTRIES: StudentObserverEntry[] = [
  {
    id: 'obs-entry-1',
    studentId: 'usr-stud-1',
    studentName: 'Sofía Ramírez Díaz',
    studentDocument: 'TI 1.025.789.444',
    groupId: 'grp-pel-01',
    groupName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    date: '2026-03-19',
    entryType: 'felicitacion_merito',
    title: 'Felicitación y Mérito Técnico por Servicio en Salón Escuela',
    description:
      'Se hace un reconocimiento especial a la estudiante por la calidad técnica, pulcritud y trato humano brindado a su modelo durante la práctica de Balayage. Cumplió con los tiempos estipulados y dejó la estación de trabajo impecable.',
    studentCommitment: 'Continuar manteniendo el estándar de excelencia para el ciclo de graduación.',
    guardianNotified: false,
    authorId: 'usr-teach-1',
    authorName: 'Prof. Elena Restrepo',
    authorRole: 'teacher',
    status: 'cumplido_cerrado',
    createdAt: '2026-03-19 06:00 PM',
  },
  {
    id: 'obs-entry-2',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    studentDocument: 'TI 1.032.441.982',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    date: '2026-03-11',
    entryType: 'falta_bioseguridad',
    title: 'Llamado de Atención: Falta de Bata Antifluidos y Careta de Protección',
    description:
      'Durante el taller de afeitado con navaja, el alumno se presentó sin la bata reglamentaria de la academia y no portaba careta de bioseguridad. Se le recordó que el protocolo de salud municipal exige estos implementos para evitar suspensiones sanitarias.',
    studentCommitment:
      'El estudiante se compromete a portar su uniforme completo (bata negra bordada con logo institucional, guantes y careta) en cada sesión práctica sin excepción.',
    guardianNotified: true,
    authorId: 'usr-admin-3',
    authorName: 'Lic. Gabriel Torres (Coordinación)',
    authorRole: 'admin',
    status: 'en_seguimiento',
    createdAt: '2026-03-11 02:30 PM',
  },
  {
    id: 'obs-entry-3',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Castro Gómez',
    studentDocument: 'TI 1.032.441.982',
    groupId: 'grp-barb-02',
    groupName: 'Taller Máster de Barbería Profesional, Fade & Barba',
    date: '2026-03-18',
    entryType: 'compromiso_academico',
    title: 'Acuerdo de Nivelación en Técnicas de Corte con Tijera',
    description:
      'Reunión académica con el docente instructor para fortalecer el ángulo de elevación a 45° y 90° en cabello largo. Se programan 4 horas adicionales de taller los viernes.',
    studentCommitment: 'Asistir con modelo puntual a las sesiones de refuerzo programadas.',
    guardianNotified: false,
    authorId: 'usr-teach-2',
    authorName: 'Prof. Marcos Silva',
    authorRole: 'teacher',
    status: 'activo',
    createdAt: '2026-03-18 05:00 PM',
  },
];

export const INITIAL_ACADEMY_NOTICES: AcademyNotice[] = [
  {
    id: 'not-promo-1',
    title: '🔥 Super Promo Estudiantil: 35% OFF en Kit de Tijeras Japonesas Titanio & Máquinas Wahl',
    content:
      '¡Atención estudiantes de Arte & Estilo! Por convenio institucional con Distribuidores Oficiales de Belleza, habilitamos un 35% de descuento exclusivo en kits profesionales para prácticas de salón: set de tijera de corte 6.0" en titanio + microdentada de pulir + capa impermeable antifluidos + máquina Wahl Legend con cuchilla Crunch.\n\nPromoción válida únicamente para estudiantes activos con carnet digital o constancia de matrícula.',
    category: 'promocion',
    targetAudience: 'estudiantes',
    authorName: 'Lic. Carlos Mendoza',
    authorRole: 'Dirección General Arte & Estilo',
    pinned: true,
    publishedAt: '2026-03-22',
    badgeText: '🔥 35% Descuento Estudiantil',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
    ],
    discountCode: 'ESTUDIANTE35-KIT',
    discountPercent: 35,
    validUntil: '2026-04-15',
    actionButtonText: 'Aprovechar Descuento en Tesorería',
    actionTab: 'finances',
    likes: 42,
    likedUserIds: ['usr-stud-1', 'usr-stud-2'],
    showAsPopupOnLogin: true,
  },
  {
    id: 'not-event-1',
    title: '🎉 Gran Pasarela & Gala Anual de Belleza "Arte & Estilo 2026": Convocatoria de Estilistas',
    content:
      'Llega el evento más esperado del año: Nuestra Gran Pasarela y Gala de Alta Peluquería, Maquillaje de Fantasía y Barbería Urbana. Tendremos pasarela en vivo, alfombra roja, prensa especializada y jurados internacionales de las principales casas de cosméticos.\n\nInscripción de colecciones de grado y peinados de vanguardia abierta hasta el 10 de abril en coordinación.',
    category: 'evento',
    targetAudience: 'todos',
    authorName: 'Dra. Sofía Valenzuela',
    authorRole: 'Directora Académica',
    pinned: true,
    publishedAt: '2026-03-21',
    eventDate: '2026-04-18',
    eventTime: '06:00 PM - 10:30 PM',
    eventLocation: 'Auditorio Metropolitano de Convenciones & Salón Principal',
    badgeText: '🎟️ Evento Magno Institucional',
    imageUrl: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
    ],
    actionButtonText: 'Ver Detalles & Postular mi Look',
    actionTab: 'notices',
    likes: 68,
    likedUserIds: ['usr-stud-1', 'usr-stud-3'],
    showAsPopupOnLogin: true,
  },
  {
    id: 'not-gallery-1',
    title: '📸 Galería de Trabajos Reales: Transformaciones de Balayage & Alisados de Nuestras Alumnas',
    content:
      '¡Felicitaciones a las alumnas del ciclo de Colorimetría y Estilismo por los resultados obtenidos en la jornada de salón escuela! Compartimos los trabajos destacados de esta semana: balayages caramelo sin maltratar la fibra capilar, alisados de keratina orgánica y ondas al agua glam.\n\nRecuerden documentar sus antes y después para su bitácora de prácticas y portafolio profesional.',
    category: 'galeria_fotos',
    targetAudience: 'estudiantes',
    authorName: 'Prof. Elena Restrepo',
    authorRole: 'Docente Máster en Colorimetría',
    pinned: false,
    publishedAt: '2026-03-20',
    badgeText: '✨ Orgullo Estudiantil',
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=800&auto=format&fit=crop&q=80',
    ],
    actionButtonText: 'Subir Mi Trabajo a Bitácora',
    actionTab: 'practices',
    likes: 54,
    likedUserIds: ['usr-stud-1'],
    showAsPopupOnLogin: false,
  },
  {
    id: 'not-masterclass-1',
    title: '👑 Masterclass Internacional: "Fade Urbano, Hair Tattoo & Técnicas de Navaja Libre"',
    content:
      'Nos complace anunciar la visita del estilista y barbero internacional invitado para una clase magistral teórico-práctica de 4 horas sobre técnicas de navaja libre, degradados milimétricos y visajismo de barba.\n\nCupos limitados para garantizar estaciones de práctica individuales. Certificado internacional incluido.',
    category: 'masterclass',
    targetAudience: 'todos',
    authorName: 'Prof. Marcos Silva',
    authorRole: 'Docente Máster en Barbería Urbana',
    pinned: true,
    publishedAt: '2026-03-18',
    eventDate: '2026-04-05',
    eventTime: '02:00 PM - 06:00 PM',
    eventLocation: 'Barber Studio Academy - Bloque A',
    badgeText: '👑 Masterclass VIP',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    ],
    actionButtonText: 'Apartar Cupo Gratuito',
    actionTab: 'calendar',
    likes: 39,
    likedUserIds: ['usr-stud-2'],
    showAsPopupOnLogin: true,
  },
  {
    id: 'not-1',
    title: '📢 Convocatoria de Modelos Reales: Jornada Balayage & Decoloración',
    content:
      'Estimados estudiantes de Peluquería y Colorimetría: Este sábado de 9:00 AM a 2:00 PM se llevará a cabo la jornada de atención de salón escuela con modelos reales. Cada estudiante debe tener confirmada su modelo para el diagnóstico previo y prueba de mechón el viernes. Insumos subsidiados por la academia.',
    category: 'practicas_modelos',
    targetAudience: 'estudiantes',
    authorName: 'Prof. Elena Restrepo',
    authorRole: 'Docente Máster en Colorimetría',
    pinned: false,
    publishedAt: '2026-03-20',
    eventDate: '2026-03-28',
    badgeText: 'Salón Escuela',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
    likes: 27,
    likedUserIds: [],
    showAsPopupOnLogin: false,
  },
  {
    id: 'not-3',
    title: '⚠️ Recordatorio Obligatorio: Inspección de Kits de Bioseguridad y Batas',
    content:
      'Por disposición de la Secretaría de Salud y el Comité de Calidad de Arte & Estilo, a partir del lunes no se permitirá el ingreso al área técnica sin: Bata negra institucional antifluidos, tapabocas termosellado, guantes de nitrilo del tono reglamentario y guardián personal de cortopunzantes para barberos.',
    category: 'urgente',
    targetAudience: 'todos',
    authorName: 'Lic. Gabriel Torres',
    authorRole: 'Coordinación Académica & Seguridad',
    pinned: false,
    publishedAt: '2026-03-16',
    badgeText: 'Bioseguridad',
    likes: 19,
    likedUserIds: [],
    showAsPopupOnLogin: false,
  },
  {
    id: 'not-4',
    title: '🎓 Apertura de Inscripciones para Ceremonia de Grados - Ciclo 2026-I',
    content:
      'Los estudiantes que tengan aprobado el 100% de su pensum académico y hayan cumplido con las 250 horas de prácticas certificadas en salón escuela pueden radicar sus documentos de paz y salvo en Secretaría Académica hasta el 15 de abril.',
    category: 'secretaria',
    targetAudience: 'estudiantes',
    authorName: 'Dra. Sofía Valenzuela',
    authorRole: 'Directora Académica',
    pinned: false,
    publishedAt: '2026-03-15',
    eventDate: '2026-05-10',
    badgeText: 'Grados Oficiales',
    likes: 45,
    likedUserIds: ['usr-stud-1', 'usr-stud-2', 'usr-stud-3'],
    showAsPopupOnLogin: false,
  },
];

export const INITIAL_TEACHER_STUDENT_MESSAGES: TeacherStudentMsg[] = [
  {
    id: 'ts-msg-1',
    senderId: 'usr-stud-1',
    senderName: 'Sofía Ramírez Díaz',
    senderRole: 'student',
    senderAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    recipientId: 'usr-teach-1',
    recipientName: 'Prof. Elena Restrepo',
    recipientRole: 'teacher',
    recipientAvatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    subject: 'Duda sobre la fórmula del matiz para mi modelo del sábado',
    message:
      'Hola profe Elena, buenas tardes. Para mi modelo del sábado, tiene una base 5 castaño claro teñida y quiero llegar a un fondo 8 cobrizo dorado para neutralizar con 8.12. ¿Me recomienda usar peróxido de 10 o 20 volúmenes en el matiz en húmedo?',
    timestamp: '2026-03-21 03:20 PM',
    read: true,
  },
  {
    id: 'ts-msg-2',
    senderId: 'usr-teach-1',
    senderName: 'Prof. Elena Restrepo',
    senderRole: 'teacher',
    senderAvatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    recipientId: 'usr-stud-1',
    recipientName: 'Sofía Ramírez Díaz',
    recipientRole: 'student',
    recipientAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    subject: 'Re: Duda sobre la fórmula del matiz para mi modelo del sábado',
    message:
      '¡Hola Sofía! Muy buena pregunta. Siempre que matizamos sobre cabello previamente decolorado que está húmedo, usa peróxido de 10 volúmenes en proporción 1:1.5 para depositar pigmento sin aclarar el cabello natural de la raíz. No dejes pasar más de 12 a 15 minutos en el lavacabezas. Recuerda traer el plex para proteger la hebra.',
    timestamp: '2026-03-21 04:05 PM',
    read: true,
  },
  {
    id: 'ts-msg-3',
    senderId: 'usr-stud-2',
    senderName: 'Mateo Castro Gómez',
    senderRole: 'student',
    senderAvatar:
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    recipientId: 'usr-teach-2',
    recipientName: 'Prof. Marcos Silva',
    recipientRole: 'teacher',
    recipientAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    subject: 'Calibración de la máquina Wahl Magic Clip',
    message:
      'Profesor Marcos, ya compré la cuchilla de cerámica que me recomendó para la máquina. ¿Podría revisarme la calibración mañana antes de empezar el taller para verificar que no muerda la piel del modelo?',
    timestamp: '2026-03-22 09:10 AM',
    read: true,
  },
  {
    id: 'ts-msg-4',
    senderId: 'usr-teach-2',
    senderName: 'Prof. Marcos Silva',
    senderRole: 'teacher',
    senderAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    recipientId: 'usr-stud-2',
    recipientName: 'Mateo Castro Gómez',
    recipientRole: 'student',
    recipientAvatar:
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    subject: 'Re: Calibración de la máquina Wahl Magic Clip',
    message:
      'Excelente Mateo. Llega 15 minutos antes a las 8:45 AM en la estación 2 de barbería y la alineamos al milímetro con el destornillador plano. Recuerda traer el aceite lubricante.',
    timestamp: '2026-03-22 10:00 AM',
    read: true,
  },
];
