import {
  CallCenterScheduleItem,
  AgentEnrollmentRecord,
  AgentCommissionSummary,
  AdminAgentMessage,
} from '../types';

export const INITIAL_CALL_CENTER_SCHEDULES: CallCenterScheduleItem[] = [
  {
    id: 'sched-01',
    prospectName: 'Mariana Gómez Quintero',
    phone: '+57 312 884 1029',
    email: 'mariana.gomez@gmail.com',
    programOfInterest: 'Técnico Laboral en Peluquería Integral & Estilismo',
    preferredShift: 'Mañana',
    scheduledDate: new Date().toISOString().slice(0, 10),
    scheduledTime: '10:30',
    type: 'visita_sede',
    status: 'pendiente',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    notes: 'Interesada en ver las estaciones de balayage y lavacabezas. Viene con su tía.',
    createdAt: '2026-09-20 09:15',
  },
  {
    id: 'sched-02',
    prospectName: 'Julián David Cárdenas',
    phone: '+57 319 443 8812',
    email: 'julian.barber99@hotmail.com',
    programOfInterest: 'Técnico en Barbería Profesional & Diseños Urbanos',
    preferredShift: 'Sábados',
    scheduledDate: new Date().toISOString().slice(0, 10),
    scheduledTime: '14:00',
    type: 'llamada_seguimiento',
    status: 'pendiente',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    notes: 'Trabaja entre semana. Quiere saber si el curso de sábados incluye máquina patillera y tijeras.',
    createdAt: '2026-09-21 11:30',
  },
  {
    id: 'sched-03',
    prospectName: 'Tatiana Lucía Benítez',
    phone: '+57 311 905 4421',
    email: 'tatiana.nails@gmail.com',
    programOfInterest: 'Técnico en Manicura Rusa, Polygel & Nail Art',
    preferredShift: 'Tarde',
    scheduledDate: new Date().toISOString().slice(0, 10),
    scheduledTime: '16:00',
    type: 'cierre_matricula',
    status: 'pendiente',
    agentId: 'usr-agent-2',
    agentName: 'Valentina Osorio',
    notes: 'Confirmó que viene a pagar la cuota inicial de $350.000 en efectivo en caja.',
    createdAt: '2026-09-21 15:45',
  },
  {
    id: 'sched-04',
    prospectName: 'Carlos Andrés Meza',
    phone: '+57 314 221 7890',
    email: 'carlos.meza@yahoo.com',
    programOfInterest: 'Técnico en Barbería Profesional & Diseños Urbanos',
    preferredShift: 'Mañana',
    scheduledDate: '2026-09-24',
    scheduledTime: '11:00',
    type: 'visita_sede',
    status: 'pendiente',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    notes: 'Quiere conocer al profesor Marcos Silva y ver la clase práctica de fade.',
    createdAt: '2026-09-22 14:00',
  },
  {
    id: 'sched-05',
    prospectName: 'Daniela Andrea Rojas',
    phone: '+57 320 671 9901',
    email: 'daniela.rojas@gmail.com',
    programOfInterest: 'Técnico Laboral en Peluquería Integral & Estilismo',
    preferredShift: 'Tarde',
    scheduledDate: '2026-09-18',
    scheduledTime: '15:30',
    type: 'cierre_matricula',
    status: 'matriculado',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    notes: 'Matrícula formalizada exitosamente con abono de $450.000.',
    createdAt: '2026-09-18 16:00',
  },
];

export const INITIAL_AGENT_ENROLLMENTS: AgentEnrollmentRecord[] = [
  {
    id: 'enr-agent-01',
    studentId: 'usr-stud-1',
    studentName: 'Valentina Restrepo',
    studentDocument: 'CC 1.020.899.412',
    studentPhone: '+57 316 456 7890',
    studentEmail: 'valentina.peluqueria@gmail.com',
    guardianName: 'Gladys Restrepo (Madre)',
    guardianPhone: '+57 315 221 9900',
    programName: 'Técnico Laboral en Peluquería Integral',
    groupId: 'grp-peluqueria-1',
    groupName: 'Técnico en Peluquería Integral (G1)',
    shift: 'Mañana (8:00 a.m. - 12:00 m.)',
    enrollmentDate: '2026-09-02',
    totalTuitionFee: 2400000,
    initialPayment: 450000,
    paymentMethod: 'Transferencia Bancaria',
    voucherNumber: 'REC-MAT-2026-091',
    discountAmount: 0,
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    commissionEarned: 50000,
    commissionStatus: 'aprobada',
    notes: 'Estudiante con excelente vocación para colorimetría. Pagó kit inicial.',
    receiptGenerated: true,
  },
  {
    id: 'enr-agent-02',
    studentId: 'usr-stud-2',
    studentName: 'Mateo Holguín',
    studentDocument: 'CC 1.033.456.789',
    studentPhone: '+57 318 678 1234',
    studentEmail: 'mateo.barber@gmail.com',
    guardianName: 'Mateo Holguín (Independiente)',
    guardianPhone: '+57 318 678 1234',
    programName: 'Técnico en Barbería Profesional & Fade',
    groupId: 'grp-barberia-1',
    groupName: 'Barbería & Cortes Urbanos (G1)',
    shift: 'Tarde (2:00 p.m. - 6:00 p.m.)',
    enrollmentDate: '2026-09-05',
    totalTuitionFee: 2100000,
    initialPayment: 350000,
    paymentMethod: 'Nequi',
    voucherNumber: 'REC-MAT-2026-092',
    discountAmount: 100000,
    discountAuthorizedBy: 'Lic. Carlos Mendoza (Admin)',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    commissionEarned: 50000,
    commissionStatus: 'aprobada',
    notes: 'Descuento del 5% aprobado por administración por pago pronto de inscripción.',
    receiptGenerated: true,
  },
  {
    id: 'enr-agent-03',
    studentId: 'usr-stud-3',
    studentName: 'Camila Andrea Soto',
    studentDocument: 'CC 1.018.990.231',
    studentPhone: '+57 319 890 1234',
    studentEmail: 'camila.nails@gmail.com',
    guardianName: 'Roberto Soto (Padre)',
    guardianPhone: '+57 311 445 6677',
    programName: 'Técnico en Manicura & Polygel',
    groupId: 'grp-manicura-1',
    groupName: 'Manicura & Estilismo de Uñas (G1)',
    shift: 'Sábados (8:00 a.m. - 2:00 p.m.)',
    enrollmentDate: '2026-09-10',
    totalTuitionFee: 1900000,
    initialPayment: 300000,
    paymentMethod: 'Efectivo',
    voucherNumber: 'REC-MAT-2026-093',
    discountAmount: 0,
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    commissionEarned: 50000,
    commissionStatus: 'aprobada',
    notes: 'Interesada especialmente en técnicas de encapsulado y 3D en polygel.',
    receiptGenerated: true,
  },
  {
    id: 'enr-agent-04',
    studentId: 'usr-stud-4',
    studentName: 'Daniela Andrea Rojas',
    studentDocument: 'CC 1.045.678.912',
    studentPhone: '+57 320 671 9901',
    studentEmail: 'daniela.rojas@gmail.com',
    guardianName: 'Daniela Rojas',
    guardianPhone: '+57 320 671 9901',
    programName: 'Técnico Laboral en Peluquería Integral',
    groupId: 'grp-peluqueria-1',
    groupName: 'Técnico en Peluquería Integral (G1)',
    shift: 'Tarde (2:00 p.m. - 6:00 p.m.)',
    enrollmentDate: '2026-09-18',
    totalTuitionFee: 2400000,
    initialPayment: 450000,
    paymentMethod: 'Daviplata',
    voucherNumber: 'REC-MAT-2026-094',
    discountAmount: 0,
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    commissionEarned: 50000,
    commissionStatus: 'pendiente',
    notes: 'Matrícula completada tras visita presencial el 18 de Septiembre.',
    receiptGenerated: true,
  },
  {
    id: 'enr-agent-05',
    studentId: 'usr-stud-5',
    studentName: 'Santiago Londoño',
    studentDocument: 'CC 1.028.334.901',
    studentPhone: '+57 317 554 2210',
    studentEmail: 'santiago.fade@gmail.com',
    guardianName: 'Santiago Londoño',
    guardianPhone: '+57 317 554 2210',
    programName: 'Técnico en Barbería Profesional & Fade',
    groupId: 'grp-barberia-1',
    groupName: 'Barbería & Cortes Urbanos (G1)',
    shift: 'Mañana (8:00 a.m. - 12:00 m.)',
    enrollmentDate: '2026-09-12',
    totalTuitionFee: 2100000,
    initialPayment: 350000,
    paymentMethod: 'Efectivo',
    voucherNumber: 'REC-MAT-2026-095',
    discountAmount: 0,
    agentId: 'usr-agent-2',
    agentName: 'Valentina Osorio',
    commissionEarned: 50000,
    commissionStatus: 'aprobada',
    notes: 'Vino recomendado por ex-alumno de la academia.',
    receiptGenerated: true,
  },
];

export const INITIAL_AGENT_COMMISSIONS: AgentCommissionSummary[] = [
  {
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    month: '2026-09',
    enrollmentCount: 4,
    baseCommissionTotal: 200000, // 4 x $50.000
    bonusAmount: 0, // Bono se activa a las 5 matrículas (+$100.000)
    totalCommission: 200000,
    status: 'pendiente',
  },
  {
    agentId: 'usr-agent-2',
    agentName: 'Valentina Osorio',
    month: '2026-09',
    enrollmentCount: 1,
    baseCommissionTotal: 50000,
    bonusAmount: 0,
    totalCommission: 50000,
    status: 'pendiente',
  },
];

export const INITIAL_ADMIN_AGENT_MESSAGES: AdminAgentMessage[] = [
  // CANAL GENERAL (VENTAS & DIRECCIÓN)
  {
    id: 'aam-gen-01',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-admin-1',
    senderName: 'Lic. Carlos Mendoza (Director)',
    senderRole: 'admin',
    channelId: 'general',
    message: '🌅 ¡Buenos días equipo comercial de Arte y Estilo! Para este mes tenemos meta institucional de 25 nuevas matrículas. Hoy inicia la campaña de pauta digital para el Técnico en Peluquería Integral y Barbería. Quien cierre 5 o más matrículas activará bono automático de $100.000 COP.',
    timestamp: '08:00 AM',
    date: '2026-09-20',
    type: 'text',
    priority: 'normal',
    read: true,
  },
  {
    id: 'aam-gen-02',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-agent-1',
    senderName: 'Camila Morales (Líder Ventas)',
    senderRole: 'agent',
    channelId: 'general',
    message: '¡Recibido Don Carlos! Ya tenemos 14 prospectos en agenda de seguimiento para hoy. Valentina y yo estamos cubriendo llamadas telefónicas y WhatsApp en simultáneo. Vamos con toda por esa meta 🚀💄.',
    timestamp: '08:15 AM',
    date: '2026-09-20',
    type: 'text',
    priority: 'normal',
    read: true,
  },
  {
    id: 'aam-gen-03',
    agentId: 'usr-agent-2',
    agentName: 'Valentina Osorio',
    senderId: 'usr-agent-2',
    senderName: 'Valentina Osorio (Asesora)',
    senderRole: 'agent',
    channelId: 'general',
    message: '🎉 ¡Confirmada matrícula de Santiago Londoño en Barbería Urbana! Ya realizó abono en efectivo por $350.000 en caja. ¡Sumamos otro cupo cerrado!',
    timestamp: '03:40 PM',
    date: '2026-09-21',
    type: 'text',
    priority: 'normal',
    read: true,
  },
  {
    id: 'aam-gen-04',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-admin-3',
    senderName: 'Lic. Gabriel Torres (Coordinador)',
    senderRole: 'admin',
    channelId: 'general',
    message: '📢 Atención vendedoras: El salón de Manicura & Polygel de los Sábados tiene únicamente 4 cupos disponibles. Prioricen a los prospectos que abonen de inmediato para garantizar reserva.',
    timestamp: '09:30 AM',
    date: '2026-09-22',
    type: 'urgent_alert',
    priority: 'urgente',
    read: true,
  },

  // CANAL MESA DE APROBACIONES & DESCUENTOS
  {
    id: 'aam-appr-01',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-agent-1',
    senderName: 'Camila Morales',
    senderRole: 'agent',
    channelId: 'approvals',
    message: '🏷️ URGENTE: Tengo en línea a Mariana Gómez Quintero. Está lista para pagar matrícula de Peluquería Integral ($2.400.000) si le concedemos 10% de descuento en el arancel inicial ($240.000). Viene con su tía a pagar en efectivo. ¿Me autorizan el descuento?',
    timestamp: '10:15 AM',
    date: '2026-09-23',
    type: 'discount_request',
    priority: 'aprobacion_inmediata',
    quoteProspectName: 'Mariana Gómez Quintero',
    quoteProgramName: 'Técnico Laboral en Peluquería Integral & Estilismo',
    discountRequestData: {
      prospectName: 'Mariana Gómez Quintero',
      programName: 'Técnico Laboral en Peluquería Integral & Estilismo',
      standardFee: 2400000,
      discountPercent: 10,
      discountedFee: 2160000,
      status: 'pendiente',
    },
    read: false,
  },
  {
    id: 'aam-appr-02',
    agentId: 'usr-agent-2',
    agentName: 'Valentina Osorio',
    senderId: 'usr-agent-2',
    senderName: 'Valentina Osorio',
    senderRole: 'agent',
    channelId: 'approvals',
    message: '🏷️ Prospecto Tatiana Benítez solicita fraccionar el pago de matrícula inicial de Manicura ($350.000) en 2 cuotas quincenales de $175.000. ¿Autorizado?',
    timestamp: '11:20 AM',
    date: '2026-09-22',
    type: 'discount_request',
    priority: 'urgente',
    quoteProspectName: 'Tatiana Lucía Benítez',
    quoteProgramName: 'Técnico en Manicura & Polygel',
    discountRequestData: {
      prospectName: 'Tatiana Lucía Benítez',
      programName: 'Técnico en Manicura Rusa & Polygel',
      standardFee: 1900000,
      discountPercent: 5,
      discountedFee: 1805000,
      status: 'aprobado',
      authorizedBy: 'Lic. Carlos Mendoza (Director General)',
    },
    read: true,
  },

  // CANAL SOPORTE RÁPIDO & DUDAS DE CLIENTES
  {
    id: 'aam-sup-01',
    agentId: 'usr-agent-2',
    agentName: 'Valentina Osorio',
    senderId: 'usr-agent-2',
    senderName: 'Valentina Osorio',
    senderRole: 'agent',
    channelId: 'support',
    message: '❓ Pregunta frecuente de prospecto: ¿El kit de instrumental para Barbería incluye la patillera inalámbrica o solo la máquina de corte principal?',
    timestamp: '02:10 PM',
    date: '2026-09-22',
    type: 'capacity_query',
    priority: 'normal',
    read: true,
  },
  {
    id: 'aam-sup-02',
    agentId: 'usr-agent-2',
    agentName: 'Valentina Osorio',
    senderId: 'usr-admin-3',
    senderName: 'Lic. Gabriel Torres',
    senderRole: 'admin',
    channelId: 'support',
    message: '💡 Respuesta oficial: El kit institucional de Barbería incluye Máquina de Corte profesional V9000 + Patillera Trimmer inalámbrica de detalle + juego de 8 peines guía + navajín de acero. Pueden asegurarle al estudiante que viene 100% completo para iniciar prácticas de fade desde la segunda semana.',
    timestamp: '02:18 PM',
    date: '2026-09-22',
    type: 'text',
    priority: 'normal',
    read: true,
  },

  // CHAT DIRECTO 1 A 1 (Camila Morales <-> Lic. Carlos Mendoza)
  {
    id: 'aam-01',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-agent-1',
    senderName: 'Camila Morales',
    senderRole: 'agent',
    recipientId: 'usr-admin-1',
    recipientName: 'Lic. Carlos Mendoza',
    channelId: 'dm-usr-agent-1-usr-admin-1',
    message: 'Hola Don Carlos, tengo en línea al prospecto Mateo Holguín para Barbería Sábados. Tiene el 100% de disposición de matricularse hoy mismo si le concedemos un descuento del 5% en la matrícula inicial ($100.000). ¿Me autoriza el descuento?',
    timestamp: '10:45 AM',
    date: '2026-09-05',
    type: 'discount_request',
    discountRequestData: {
      prospectName: 'Mateo Holguín',
      programName: 'Barbería Profesional & Cortes Urbanos',
      standardFee: 2100000,
      discountPercent: 5,
      discountedFee: 2000000,
      status: 'aprobado',
      authorizedBy: 'Lic. Carlos Mendoza (Director General)',
    },
    read: true,
  },
  {
    id: 'aam-02',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-admin-1',
    senderName: 'Lic. Carlos Mendoza',
    senderRole: 'admin',
    recipientId: 'usr-agent-1',
    recipientName: 'Camila Morales',
    channelId: 'dm-usr-agent-1-usr-admin-1',
    message: '¡Aprobado Camila! Procede con la matrícula de Mateo con el descuento de $100.000. Excelente gestión para cerrar el cupo de barbería. Queda registrado en el sistema.',
    timestamp: '10:48 AM',
    date: '2026-09-05',
    type: 'discount_approved',
    read: true,
  },
  {
    id: 'aam-03',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-agent-1',
    senderName: 'Camila Morales',
    senderRole: 'agent',
    recipientId: 'usr-admin-1',
    recipientName: 'Lic. Carlos Mendoza',
    channelId: 'dm-usr-agent-1-usr-admin-1',
    message: 'Muchas gracias Don Carlos, ya registré la matrícula y le envié el comprobante oficial por WhatsApp. Voy por la 5ta matrícula del mes para alcanzar el primer bono comercial 🎯.',
    timestamp: '10:52 AM',
    date: '2026-09-05',
    type: 'text',
    read: true,
  },
  {
    id: 'aam-04',
    agentId: 'usr-agent-1',
    agentName: 'Camila Morales',
    senderId: 'usr-admin-1',
    senderName: 'Lic. Carlos Mendoza',
    senderRole: 'admin',
    recipientId: 'usr-agent-1',
    recipientName: 'Camila Morales',
    channelId: 'dm-usr-agent-1-usr-admin-1',
    message: '¡Adelante Camila! Recuerden que el grupo de Peluquería Integral de la Mañana ya tiene 16 estudiantes, confirmada su apertura. Enfóquense en el turno de la Tarde que tiene 12 inscritos.',
    timestamp: '11:00 AM',
    date: '2026-09-05',
    type: 'text',
    read: true,
  },
];

export const CALL_CENTER_WHATSAPP_TEMPLATES = [
  {
    id: 'tpl-bienvenida',
    title: '1. Bienvenida & Asesoría Personalizada',
    category: 'Presentación',
    text: `¡Hola [Nombre]! ✨ Te saluda [Agente] de la Academia de Belleza Profesional *Arte & Estilo* ✂️🎨.
Vimos tu interés en formarte en el mundo de la belleza. Contamos con programas avalados, docentes campeones nacionales y prácticas 100% reales en nuestro propio salón escuela con modelos reales.
¿Te gustaría que te comparta el pensum y las opciones de horarios (Mañana, Tarde o Sábados)?`,
  },
  {
    id: 'tpl-pensum-costos',
    title: '2. Pensum, Inversión & Facilidades de Pago',
    category: 'Precios & Módulos',
    text: `¡Excelente [Nombre]! 🌟 Nuestro programa de *[Programa]* tiene una duración de [Meses] meses con certificación técnica laboral.
Incluye:
✅ Módulos de Tricología, Colorimetría, Cortes de Vanguardia y Bioseguridad.
✅ Prácticas reales supervisadas en Salón Escuela.
✅ Kit de instrumental inicial y carné estudiantil.

💰 *Inversión:* Cuota inicial accesible y mensualidades diferidas. ¿Te gustaría agendar una llamada breve para explicarte las facilidades de financiación?`,
  },
  {
    id: 'tpl-invitacion-sede',
    title: '3. Invitación a Conocer la Sede & Salón Escuela',
    category: 'Visita Presencial',
    text: `¡Hola [Nombre]! 🏫 Te tenemos una cordial invitación: nos encantaría que vengas a conocer las instalaciones de *Arte & Estilo*.
Podrás ver en vivo a nuestros estudiantes realizando Balayage, cortes Fade y uñas Polygel en el salón escuela, y hablar directamente con nuestros instructores máster.
¿Te queda bien visitarnos este [Día] a las [Hora]? ¡Te reservamos una cortesía especial! ☕✨`,
  },
  {
    id: 'tpl-requisitos-matricula',
    title: '4. Requisitos para Asegurar el Cupo',
    category: 'Matrícula',
    text: `¡Perfecto [Nombre]! 📝 Para formalizar tu matrícula en el grupo de *[Grupo]* solo requieres:
1️⃣ Fotocopia del documento de identidad (Cédula o T.I.).
2️⃣ 1 foto 3x4 fondo blanco para el carné institucional.
3️⃣ Abono inicial de matrícula de $[ValorAbono] (recibimos Efectivo, Nequi, Daviplata o PSE).
¿Deseas que te reservemos el cupo de inmediato para no quedarte por fuera del límite de capacidad?`,
  },
  {
    id: 'tpl-recordatorio-cita',
    title: '5. Recordatorio de Cita en Sede / Llamada',
    category: 'Seguimiento',
    text: `¡Hola [Nombre]! 👋 Te recordamos tu cita programada con la Academia de Belleza *Arte & Estilo* para el día de hoy a las [Hora].
Nuestra asesora [Agente] te estará esperando para resolver todas tus dudas y darte el recorrido por las salas de estilismo. Si tienes algún contratiempo, avísanos por aquí para reprogramar. ¡Te esperamos! ✨`,
  },
  {
    id: 'tpl-felicitacion-matricula',
    title: '6. Bienvenida Oficial a la Academia (Matriculado)',
    category: 'Cierre Exitoso',
    text: `🎉 ¡FELICITACIONES [Nombre]! 🎉
Oficialmente eres parte de la familia de la *Academia de Belleza Arte & Estilo*. Tu matrícula en el programa *[Programa]* ha sido formalizada exitosamente.
📍 Grupo: [Grupo]
⏰ Horario: [Horario]
Adjunto encontrarás tu comprobante de matrícula oficial. ¡Prepárate para transformar tu talento en una profesión exitosa y rentable! ✂️💄`,
  },
];
